# bazaar-bin - prebuilt package of https://github.com/bazaar-org/bazaar
# (GNOME app store focused on flatpaks/Flathub, C + GTK4/blueprint).
#
# Upstream tags releases but ships no binaries, so build_artifact() builds
# from the release tarball.

UPSTREAM_REPO="bazaar-org/bazaar"

# Installed in CI (pacman) before build_artifact runs.
BUILD_DEPS=(meson ninja blueprint-compiler glib2-devel python-babel gettext
            gobject-introspection appstream flatpak gtk4 libadwaita
            gtksourceview5 libdex glycin glycin-gtk4 webkitgtk-6.0 json-glib
            libxmlb libyaml md4c libmalcontent libsecret libsoup3 libproxy
            libheif)

latest_version() {
  gh api "repos/$UPSTREAM_REPO/releases/latest" --jq '.tag_name' | sed 's/^v//'
}

# build_artifact <version> <output-file>
build_artifact() {
  local ver="$1" outfile="$2"
  local workdir destdir srctree
  workdir="$(mktemp -d)"
  destdir="$(mktemp -d)"

  curl -sfL "https://github.com/$UPSTREAM_REPO/archive/refs/tags/v$ver.tar.gz" | tar -xz -C "$workdir"
  srctree="$workdir/bazaar-$ver"

  meson setup "$workdir/build" "$srctree" --prefix=/usr --buildtype=release
  meson install -C "$workdir/build" --destdir "$destdir"

  # These caches are generated by pacman hooks; shipping them would cause
  # file conflicts on install.
  rm -f "$destdir/usr/share/glib-2.0/schemas/gschemas.compiled" \
        "$destdir/usr/share/applications/mimeinfo.cache" \
        "$destdir/usr/share/icons/hicolor/icon-theme.cache"

  tar --zstd --sort=name --owner=0 --group=0 --numeric-owner --mtime='@0' \
      -cf "$outfile" -C "$destdir" usr

  rm -rf "$workdir" "$destdir"
}
