# protonplus-bin - prebuilt package of https://github.com/Vysp3r/ProtonPlus
# (GTK4 + LibAdwaita compatibility-tools manager written in Vala).
#
# Upstream publishes no binary release assets, so build_artifact() compiles
# the Vala project from the release tarball (native x86_64 binary).

UPSTREAM_REPO="Vysp3r/ProtonPlus"

# Installed in CI (pacman) before build_artifact runs.
BUILD_DEPS=(meson ninja vala gtk4 libadwaita json-glib libgee libsoup3
            libarchive gettext glib2-devel)

latest_version() {
  gh api "repos/$UPSTREAM_REPO/releases/latest" --jq '.tag_name' | sed 's/^v//'
}

# build_artifact <version> <output-file>
build_artifact() {
  local ver="$1" outfile="$2"
  local workdir destdir srctree
  workdir="$(mktemp -d)"
  destdir="$(mktemp -d)"

  curl -sfL "https://github.com/$UPSTREAM_REPO/archive/refs/tags/v$ver.tar.gz" | tar -xz -C "$workdir"
  srctree="$workdir/ProtonPlus-$ver"

  meson setup "$workdir/build" "$srctree" --prefix=/usr --buildtype=release -Dstrip=true
  meson install -C "$workdir/build" --destdir "$destdir"

  # These caches are generated by pacman hooks; shipping them would cause
  # file conflicts on install.
  rm -f "$destdir/usr/share/glib-2.0/schemas/gschemas.compiled" \
        "$destdir/usr/share/applications/mimeinfo.cache" \
        "$destdir/usr/share/icons/hicolor/icon-theme.cache"

  tar --zstd --sort=name --owner=0 --group=0 --numeric-owner --mtime='@0' \
      -cf "$outfile" -C "$destdir" usr

  rm -rf "$workdir" "$destdir"
}
